title: Games automata play
description: Technical developments on my research, topics pertaining to games, automata, logic, learning theory

url: 
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 20

navigation:
 - title: Research
   url: /index.html
 - title: Reinforcement learning
   url: /RL
 - title: By categories
   url: /category
 - title: About
   url: /about

social:
   github: https://github.com/nathanael-fijalkow
   twitter: 
   facebook: 
   email: nathanael.fijalkow@labri.fr

google_analytics: UA-21235964-7

# Disqus Comments
disqus:
    # Leave shortname blank to disable comments site-wide.
    # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
    shortname: games-automata-play

