title: Games automata play
description: Technical developments on my research, topics pertaining to games, automata, logic, learning theory

url: 
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 20

navigation:
 - title: Home
   url: /index.html
 - title: By categories
   url: /category
 - title: About
   url: /about

social:
   github: 
   twitter: 
   facebook: 
   email: nathanael.fijalkow@labri.fr

google_analytics: UA-21235964-7
