title: Games automata play
description: Technical developments about games for automata and logic

url: 
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 10

navigation:
 - title: Home
   url: /index.html
 - title: By categories
   url: /category
 - title: About
   url: /about

social:
   github: 
   twitter: 
   facebook: 
   email: nfijalkow@turing.ac.uk

google_analytics: UA-21235964-7
